### ISSUE TITLE
webpplEval doesn't work in inference

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#643]
I know webpplEval isn't technically documented, but there's a [probmods example](https://probmods.org/learning-as-conditional-inference.html#example-inferring-an-arithmetic-expression) that needs something like `eval` to build functions from strings and I was playing around with it anyway! It works just fine outside of an `Infer` statement, but seems to interfere with inference:

```
var foo = Infer({method: 'enumerate'}, function() {
  var int = randomInteger(10);
  var bar = webpplEval('3 +' + int);
  print(bar) // correctly evaluates
  condition(bar == 5);
  return int;
});
                                 
foo 
```

throws 

```
webpplEval error:
Error: factor allowed only inside inference.
```

and if you remove the condition statement, you get 

```
webpplEval error:
TypeError: t is not a function
```

The main issue here is probably deciding on the status of `webpplEval` in the language: is it a header function we want to work everywhere (in which case we might want to add it to the docs once fixed up), is it just not intended to work inside inference (in which case we might want to mention that in the docs), or is it something we don't want to expose at all?

**Comment by null-a** [comment]
> It works just fine outside of an Infer statement, but seems to interfere with inference:

This used to work, but it was broken by #565. That change resets `env` at the top of `header.wppl`, which (it turns out) has the effect of uninstalled the current coroutine when `webpplEval` is called. I'll work up a PR that fixes this.

> but there's a probmods example that needs something like eval to build functions from strings

One alternative for this case might be to use Javascript's `eval`? It looks like replacing `webpplEval` with `_top.eval` in you example works. This would also have the advantage of been *much* faster than the webppl version.

`_top` is a thing webppl uses internally. It's set to either `window` or `global` depending on whether you're in the browser or node. I'm using it here as a hack to call top-level JS functions using a member expression. I guess we'd wrap this as something like `jseval` if it's useful?

> The main issue here is probably deciding on the status of webpplEval in the language

I'll leave this to everyone else to decide, but if we do make it public I think it might be a good idea to warn users that it's super slow.

**Comment by hawkrobe** [comment]
Fantastic, thank you! And good to know about _top.eval -- I might switch to that if the example needs to be scaled up more.

**Comment by hawkrobe** [comment]
Interesting -- `_top.eval()` doesn't seem to properly evaluate strings containing "function" (although webpplEval does!)

**Comment by null-a** [comment]
if you're eval'ing a function expression, it looks like you need to wrap it in parens. So `_top.eval('(function() { ... })')` rather than `_top.eval('function() { ... }')`. Does that help?

(Don't forget you'll need to call the result of this using a member expression.)

**Comment by hawkrobe** [comment]
I saw the parens detail in the eval spec, but it looks like member expressions got me again! Thanks.
